---
codecov:
  branch: main
comment:
  behavior: default
  require_changes: true
coverage:
  range: 70..100
  status:
    changes: false
    project:
      default:
        target: 60.0
        threshold: 0
      fully_covered:
        target: 70.0
        paths:
          - checkout_last_signed_commit.py
          - tests/
    patch:
      default:
        target: 100.0
        branches: null
