---
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
      - name: Set up Python 3.11
        uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566  # v3
        with:
          python-version: "3.11"
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7
        with:
          enable-cache: true
      - run: uv run make test-with-coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac  # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
